<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Drawer Slides and Glides from KV Blum Waterloo | USACabinetHardware.com</title>
<meta name="description" content="Drawer slides by Knape & Vogt, Blum and Waterloo.  Browse cabinet drawer slides or use our selective cabinet hardware drawer slide search.">
<meta name="keywords" content="drawer slides, cabinet drawer slides, drawer guides, drawer glides, cabinet drawer guides, full-extension drawer slides, file drawer slides, file drawer runners, drawer runners, drawer tracks, undermount drawer slides, undermount drawer slides, sidemount drawer slides, sidemount drawer guides, Blum drawer slides, KV drawer slides, Knape & Vogt drawer slides, Blum SOLO drawer slides, Blum Tandem undermount drawer slides, drawer slide brackets, plastic drawer slide holder">
<!--<base url="http://www.usacabinethardware.com/">-->
<link rel="StyleSheet" type="text/css" href="main.css?v=2">

</head>
<body topmargin="0" margin-height="0" leftmargin="0" margin-width="0">
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-W2R9"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-W2R9');</script>
<!-- End Google Tag Manager -->

<div id="pageContainer">

<table align="center" width="980" border="0" cellpadding="0" cellspacing="0">
<tr>
<td>

<map name="_head">
<area shape="rect" coords="91,37,597,81" href="index.html" alt="" >
<area shape="rect" coords="888,71,980,92" href="search.html" alt="" >
<area shape="rect" coords="877,50,980,71" href="contact.html" alt="" >
<area shape="rect" coords="878,27,980,48" href="cgi-bin/usastore.pl?a=cart_display" alt="" >
<area shape="rect" coords="830,96,980,120" href="customer-care.html" alt="" >
<area shape="rect" coords="558,98,729,126" href="catches-locks.phtml" alt="" >
<area shape="rect" coords="398,96,542,126" href="drawer-slides.phtml" alt="" >
<area shape="rect" coords="303,97,382,126" href="hinges.phtml" alt="" >
<area shape="rect" coords="133,96,288,126" href="knobs-pulls.phtml" alt="" >
<area shape="rect" coords="872,0,980,25" href="cgi-bin/usastore.pl?a=checkout" alt="" >
<area shape="rect" coords="339,112,340,113" href="#" alt="" >
</map><img name="head" src="img/head.jpg" width="980" border="0" usemap="#_head" alt="USA Cabinet Hardware Logo & Navigation">

</td>
</tr>
<tr>
<td style="padding-top:30px" valign="top">
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
        <td width="50%" valign="top">
                <table border="0" cellpadding="5" cellspacing="0">
                <tr><td valign="top" style="padding-right:30px">
                <h1>Drawer Slides</h1>
<!--               <tr>
                <td align="left"><br><img src="img/head-drawer-slide-categories.gif" alt="Cabinet Drawer Slide Categories"></td>
                </tr>		-->
                <table border="2" cellspacing=0 width=100%>
                <tr>
  <?php
  $count = 1;
  $line_count = 1;
  $server = "localhost";
  $user = "edweb";
  $pass = "gh0rAc";
  $db = "edirect";
  $db_conn = new mysqli($server, $user, $pass, $db);

  $cat_query = "SELECT section_id, section_name
               FROM store_sections
               WHERE aisle_id = 3802
			   and sort_order != 0
               ORDER BY sort_order ASC";

  $stmt = $db_conn->stmt_init();
  $stmt->prepare($cat_query);
  $stmt->execute();
  $result = $stmt->get_result();

  $count = 0;
  while ($cat = $result->fetch_array()) {
          if ($count == 5) {
                  print "</tr><tr>";
          }
          $cat_id = $cat["section_id"];
          $cat_name = $cat["section_name"];
          print "<td class=\"catalogGridNav\"><a href=\"cgi-bin/usastore.pl?a=b&cnid=$cat_id\">$cat_name</a></td>";
          $count++;
  }

  $result->free();
  $stmt->close();



  ?>
  				</tr>
				</table>
				<p style="text-align:justify">
                Cabinet and furniture drawer slides come in several types: sidemount or
                undermount,     3/4 extension, full-extension or over-travel, as well as several load
                rating capacities.  We offer slides for drawers in many styles from well-known
                manufacturers like Accuride, Blum, Knape & Vogt and Waterloo.  You can
                browse
                each brand or perform a search by using the links to your right.
                </p>

                <p style="text-align:justify">
                Measuring correctly and understanding the different styles of cabinet
                drawer slides is very important.  We strive to provide you with the
                information necessary to aid you in making the right choice.  Please
                study the information carefully, measure your application with precision
                and ask questions if you aren't sure before you make your drawer slide
                purchase.  Use our reference center (links to the right) as well as
                the specifications for each slide to determine which one is right for
                your drawer.
                </p>

				<br>
                </td>
                </tr>


                <tr>
                <td>

			</tr>
			</td>
            <tr>
            <td style="padding-top:70px">
                <img src=img/head-top-10-slides.gif alt="Most Popular Drawer Slides">
                <div class=tiny>These are our top 10 most popular cabinet and furniture
                drawer slides and accessories.</div>

<?php
$catCount = 0;

$query = "SELECT tt_position, tt_name, tt_img
                        FROM top_products
                        WHERE tt_id = 5
                        ORDER BY 1
						LIMIT 10";

$stmt = $db_conn->stmt_init();
$stmt->prepare($query);
$stmt->execute();
$result = $stmt->get_result();

echo "<table border=0 width=100%>";
$count = 1;
while ($count < 3) {
        echo "<tr>";
        for ($i=1; $i<6; $i++) {
                $myrow = $result->fetch_array();
                $pid = $myrow["tt_name"];
                $imgsrc = $myrow["tt_img"];
                if ($imgsrc == '') {
                        $imgsrc = 'img-not-avail.jpg';
                }
                echo "<td class=small valign=bottom style=\"padding-bottom:40px\"><a href=\"http://www.usacabinethardware.com/cgi-bin/usastore.pl?a=di&pid=$pid\">
                        <img src=\"http://www.usacabinethardware.com/img/$imgsrc\" width=60 border=0><br>$pid</a></td>";
        }
        echo "</tr>";
        $count++;

}

$result->free();
$stmt->close();

?>

                        </table>
                </td>
                </tr>
                </table>
<br><br><br>
<div style="margin-left:100px">

</div>
        </td>
        <td class=detail valign=top width=30%>
        <div class="catNav">
        <div class="sectionHead"> DRAWER SLIDE BRANDS</div>
        <div class="sectionMain">
                <table border=0 cellpadding=0 cellspacing=0 width=90%>
                <tr>
                <td class=detail valign="top">
 <b>Accuride</b></a>
                <ul>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3802&bid=643">Browse All</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66040&bid=643">3/4 Extension</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66041&bid=643">Full Extension</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66042&bid=643">Overtravel</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3807&bid=643">Pocket Door</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66043&bid=643">Specialty</a></li>
                <li><a href="search.html">Search</a></li>
                </ul>
        <b>Fulterer</b>
                <ul>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3802&bid=705">Browse All</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66040&bid=705">3/4 Extension</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66041&bid=705">Full Extension</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66042&bid=705">Overtravel</a></li>
                <li><a href="search.html">Search</a></li>
                </ul>
                </td>
                <td class=detail valign="top">
		<b>Blum</b></a>
                <ul>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3802&bid=646">Browse All</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66040&bid=646">3/4 Extension</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66041&bid=646">Full Extension</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66042&bid=646">Overtravel</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3807&bid=646">Pocket Door</a></li>
                <li><a href="search.html">Search</a></li>
                </ul>
        <b>Knape & Vogt</b>
                <ul>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3802&bid=641">Browse All</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66040&bid=641">3/4 Extension</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66041&bid=641">Full Extension</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66042&bid=641">Overtravel</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3807&bid=641">Pocket Door</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66043&bid=641">Specialty</a></li>
                <li><a href="search.html">Search</a></li>
                </ul>


                </td>
                </tr>
				<tr>
                <td class=detail valign="top">
        <b>Topslide</b></a>
                <ul>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3802&bid=723">Browse All</a></li>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=66041&bid=723">Full Extension</a></li>
                <li><a href="search.html">Search</a></li>
                </ul>
                </table>
        </div>
        <br><br>
        <div class="sectionHead"> SEARCH FOR DRAWER SLIDES</div>
        <div class="sectionMain">
                <ul>
                <li>
                <a href="cgi-bin/usastore.pl?a=cs&t=slideSearch"><b>Cabinet Drawer Slide Search</b></a>
                <div class=small>Search our database of cabinet and furniture
                        drawer slides by
                selecting from existing terms.</div></li>
                <li>
                <a href="search.html"><b>Drawer Slide Keyword Search</b></a>
                <div class=small>Enter a product number, type or description
                to perform your own search.</div></li>
                </ul>
        </div>
        <br><br>
        <div class="sectionHead"> DRAWER SLIDE REFERENCE</div>
        <div class="sectionMain">
                <ul>
                <li>
        <a href="drawer-slide-terms.html"><b>Drawer Slide Terms</b></a>
                <div class=small>Get the low-down on the lingo in the functional cabinet
                hardware circle.  </div></li>
        <!--
                <li>
                <a href="drawer-slide-styles.html"><b>Drawer Slide Styles</b></a>
                <div class=small>Learn about the different styles of cabinet
                        and furniture drawer slides.
                </div></li>
        -->
                <li>
                <a href="docs/specs/pdf/643/AC-SLIDE-REFERENCE-GUIDE.pdf"><b>Accuride Reference Guide</b></a> (PDF)
                <div class=small>Get a quick overview of the Accuride family of
                cabinet drawer slides.
                </div></li>
                <li>
                <a href="blum-tandem.pdf"><b>Blum Tandem Drawer Slide</b></a> (PDF)
                <div class=small>All about the Blum Tandem line of cabinet
                        drawer slides.
                </div></li>
                <li>
                <a href="blum-solo.pdf"><b>Blum SOLO Drawer Slide</b></a> (PDF)
                <div class=small>All about the Blum SOLO line of cabinet
                        drawer slides.
                </div></li>
                <li>
                <a href="docs/specs/pdf/641/KV-DRAWER-SLIDE-APP-GUIDE.pdf"><b>KV Slide Application Chart</b></a> (PDF)
                <div class=small>A quick guide to the applications and raings
                of Knape & Vogt drawer slides.
                </div></li>
                <li>
                <a href="drawer-slide-faq.html"><b>Drawer Slide FAQ</b></a>
                <div class=small>Some frequently asked questions (and answers!)
                about drawer slides.
                </div></li>
                </ul>
        </div>
        </div>

        </td>
        </tr>
        </table>
</td>
</tr>
</table>

    <div id="pageFooter">

      <div class="pageFooterBox"><span><a href="knobs-pulls.phtml">Cabinet Knobs & Pulls</a></span>
 		<ul>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66000">Handle Pulls</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66002">Cabinet Knobs</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66001">Cup Pulls</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66006">Bar Pulls</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66007">Appliance Pulls</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66004">Backplates</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66003">Ring, Bail & Pendant</a></li>
          </ul>
	 </div>
	<div class="pageFooterBox"><span><a href="hinges.phtml">Cabinet Hinges</a></span>
		<ul>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66020">Inset</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66021">Overlay</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66030">Euro</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66025">Knife</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66024">Concealed</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66028">Semi-Concealed</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66029">Non-Concealed</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66022">Side Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66023">Surface Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66027">Specialty</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66026">Mounting Plates</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66032">Miscellaneous</a></li>
		</ul>
	</div>
    <div class="pageFooterBox"><span><a href="drawer-slides.phtml">Drawer Slides</a></span>
		<ul>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66040">3/4 Extension</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66041">Full Extension</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66042">Overtravel</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66044">Side Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66045">Side/Bottom Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66046">Under Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66047">Flat Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66043">Specialty</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66048">Miscellaneous</a></li>
		</ul>
	</div>
    <div class="pageFooterBox"><span><a href="catches-locks.phtml">Catches & Locks</a></span>
		<ul>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66060">Magnetic Catches</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66061">Roller Catches</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66062">Mechanical Catches</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66063">Ball & Bullet Catches</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66064">Cam Locks</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66065">Deabolt Locks</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66066">Gang Locks</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66068">Other Locks</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66067">Lock Accessories</a></li>
		</ul>
	</div>
    <div class="pageFooterBox"><span><a href="customer-care.html">Customer Care</a></span>
                <ul>
                <li><a href="policies.html#returns">Returns</a></li>
                <li><a href="policies.html#shipping">Shipping & Handling</a></li>
                <li><a href="policies.html#privacy">Privacy & Security</a></li>
                <li><a href="contact.html">Contact Us</a></li>
                <li><a href="care-faq.html">Customer Care FAQ</a></li>
                </ul>
	</div>



        <div id="copy">
        Copyright &copy; 2013 usacabinethardware.com by Everything Direct Inc.<br>
        1046 39th Ave W<br>
        West Fargo, ND 58078<br>
        1.866.570.3272<br>
        <a href="mailto:webadmin@usacabinethardware.com">webadmin</a>
        </div>
	</div>

</div>
</body>
</html>

