<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Cabinet Door Hinges | USA Cabinet Hardware</title>
<meta name="description" content="Cabinet door hinges from Amerock, Belwith-Keeler, Blum, Salice, Stanley and Youngdale.  Browse cabinet hinges or use our selective cabinet door hinge search.">
<meta name="keywords" content="cabinet door hinges, cabinet hinges, cabinet hardware hinges, kitchen cabinet hinges, kitchen cabinet door hinges, Blum concealed hinges, Blum cabinet hinges, Amerock cabinet hinges, Amerock cabinet door hinges, Belwith-Keeler cabinet hinges, Blume cabinet door hinges, Grass cabinet hinges, Grass concealed hinges, Salice, knife hinges, concealed hinges, overlay hinges, self-closing hinges, brass hinges, nickel cabinet hinges, nickel cabinet door hinges, brass cabinet door hinges, self-closing hinges, inset cabinet hinges, inset cabinet door hinges, semi-concealed cabinet hinges, hinges for cabinets, hinges for cabinet doors">

<base url="http://www.usacabinethardware.com/">
<link rel="StyleSheet" type="text/css" href="main.css?v=2">

</head>
<body topmargin="0" margin-height="0" leftmargin="0" margin-width="0">
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-W2R9"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-W2R9');</script>
<!-- End Google Tag Manager -->

<div id="pageContainer">

<table align="center" width="980" border="0" cellpadding="0" cellspacing="0">
<tr>
<td>

<map name="_head">
<area shape="rect" coords="91,37,597,81" href="index.html" alt="" >
<area shape="rect" coords="888,71,980,92" href="search.html" alt="" >
<area shape="rect" coords="877,50,980,71" href="contact.html" alt="" >
<area shape="rect" coords="878,27,980,48" href="cgi-bin/usastore.pl?a=cart_display" alt="" >
<area shape="rect" coords="830,96,980,120" href="customer-care.html" alt="" >
<area shape="rect" coords="558,98,729,126" href="catches-locks.phtml" alt="" >
<area shape="rect" coords="398,96,542,126" href="drawer-slides.phtml" alt="" >
<area shape="rect" coords="303,97,382,126" href="hinges.phtml" alt="" >
<area shape="rect" coords="133,96,288,126" href="knobs-pulls.phtml" alt="" >
<area shape="rect" coords="872,0,980,25" href="cgi-bin/usastore.pl?a=checkout" alt="" >
<area shape="rect" coords="339,112,340,113" href="#" alt="" >
</map><img name="head" src="img/head.jpg" width="980" border="0" usemap="#_head" alt="USA Cabinet Hardware Logo & Navigation">

</td>
</tr>
<tr>
<td style="padding-top:30px" valign="top">
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
        <td valign="top">
                <table border="0" cellpadding="5" cellspacing="0">
                <tr><td class="detail" valign="top" style="padding-right:30px">

                <h1>Cabinet Door Hinges</h1>
	<!--			<tr>
                <td align="left"><br><br><img src="img/head-hinge-categories.gif" alt="Kitchen Cabinet Knob and Pull Categories"></td>
                </tr> -->
                <table border="2" cellspacing=0 width=100%>
                <tr>
  <?php
  $count = 1;
  $line_count = 1;
  $server = "localhost";
  $user = "edweb";
  $pass = "gh0rAc";
  $db = "edirect";
  $db_conn = new mysqli($server, $user, $pass, $db);

  $cat_query = "SELECT section_id, section_name
               FROM store_sections
               WHERE aisle_id = 3801
               ORDER BY sort_order ASC";

  $stmt = $db_conn->stmt_init();
  $stmt->prepare($cat_query);
  $stmt->execute();
  $result = $stmt->get_result();

  $count = 0;
  while ($cat = $result->fetch_array()) {
          if ($count == 5) {
                  print "</tr><tr>";
				  $count = 0;
          }
          $cat_id = $cat["section_id"];
          $cat_name = $cat["section_name"];
          print "<td class=\"catalogGridNav\"><a href=\"cgi-bin/usastore.pl?a=b&cnid=$cat_id\">$cat_name</a></td>";
          $count++;
  }

  $result->free();
  $stmt->close();


  ?>
                        </tr>
                        </table>
				<p style="text-align:justify">
Replacing cabinet door hinges can be a tricky undertaking.  Aside from the various manufacturers and finishes, cabinet hinges come in several styles.  Overlay, inset, flush, concealed, wrap, self-closing, free-swinging, all describe the style of a hinge.  If you require help determining what style you need, please start by looking through our <a href="cabinet-hinge-terms.html">Cabinet Hinge Terms</a> and other materials
in our reference section located at the bottom right of this page. </p>

                <p style="text-align:justify">
                We hope that the information provided on our site will help you in your
                search and understanding of cabinet hinges.  If you need additional
                help, it is most beneficial if you can <a href="hinge-help.html">email</a>
                us some pictures of your existing cabinet hinges for us to review.
                </p>
                <br/>
				<p style="padding-left:30px">
				<h3><a href="hinge-help.html">CLICK HERE for cabinet hinge REPLACEMENT Help</h3></a>
				</p>
				<br/>

                </td>
                </tr>

				<tr>
                <td>

                </td>
                </tr>
                <tr>
                <td style="padding-top:70px">
                <img src="img/head-top-10-hinges.gif" alt="Most Popular Cabinet Hinges">
                <div class="tiny">These are our top 10 most popular cabinet hinges and
                mounting plates.</div>

<?php
$catCount = 0;

$query = "SELECT tt_position, tt_name, tt_img
                        FROM top_products
                        WHERE tt_id = 4
                        ORDER BY 1
						LIMIT 10";

$stmt = $db_conn->stmt_init();
$stmt->prepare($query);
$stmt->execute();
$result = $stmt->get_result();

echo "<table border=0 width=100%>";
$count = 1;
while ($count < 3) {
        echo "<tr>";
        for ($i=1; $i<6; $i++) {
                $myrow = $result->fetch_array();
                $pid = $myrow["tt_name"];
                $imgsrc = $myrow["tt_img"];
                if ($imgsrc == '') {
                        $imgsrc = 'img-not-avail.jpg';
                }
                echo "<td class=tiny valign=bottom style=\"padding-bottom:40px\"><a href=\"http://www.usacabinethardware.com/cgi-bin/usastore.pl?a=di&pid=$pid\">
                        <img src=\"http://www.usacabinethardware.com/img/$imgsrc\" width=80 border=0><br>$pid</a></td>";
        }
        echo "</tr>";
        $count++;

}

$result->free();
$stmt->close();

?>

                        </table>
                </td>
                </tr>
                </table>
				<br><br>

        </td>
        <td class="detail" valign="top" width="28%">
        <div class="catNav">
        <div class="sectionHead"> CABINET HINGE BRANDS</div>
        <div class="sectionMain">
                <table border="0" cellpadding="0" cellspacing="0" width="90%">
                <tr>
                <td class="detail">
        <b>Amerock</b></a>
                <ul>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3801&bid=639">Browse All</a></li>
                <li><a href="search.html">Search</a></li>
                </ul>
        <b>Hickory Hardware</b>
                <ul>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3801&bid=640">Browse All</a></li>
                <li><a href="search.html">Search</a></li>
                </ul></td>
                <td class="detail">
        <b>Blum</b>
                <ul>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3801&bid=646">Browse All</a></li>
                <li><a href="search.html">Search</a></li>
                </ul>
        <b>Grass</b>
                <ul>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3801&bid=647">Browse All</a></li>
                <li><a href="search.html">Search</a></li>
                </ul>
                </td>
                </tr>
                <tr><td class="detail">
        <b>Salice</b>
                <ul>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3801&bid=718">Browse All</a></li>
                <li><a href="search.html">Search</a></li>
                </ul>
                </td>
                <td class="detail">
        <b>Youngdale</b>
                <ul>
                <li><a href="cgi-bin/usastore.pl?a=b&cnid=3801&bid=648">Browse All</a></li>
                <li><a href="search.html">Search</a></li>
                </ul>
                </td>
                </tr>
                </table>
        </div>
        <br><br>
        <div class="sectionHead"> SEARCH FOR HINGES - MOUNTING PLATES</div>
        <div class="sectionMain">
                <ul>
                <li>
        <a href="cgi-bin/usastore.pl?a=cs&t=hingeSearch"><b>Kitchen Cabinet Hinge Search</b></a>
                <div class=small>Search our database of functional cabinet hardware by
                selecting from existing terms.</div></li>
                <li>
                <a href="search.html"><b>Cabinet Hinge Keyword Search</b></a>
                <div class=small>Enter a product number, type or description
                to perform your own search.</div></li>
                </ul>
        </div>
        <br><br>
        <div class="sectionHead">CABINET HINGE REFERENCE</div>
        <div class="sectionMain">
                <ul>
                <li>
                <a href="cabinet-hinge-terms.html"><b>Cabinet Hinge Terms</b></a>
                <div class=small>Get the low-down on the lingo in the functional
                        cabinet hardware circle.
						</div>
						</li>
				<li>
                <a href="cabinet-hinge-faq.html"><b>Cabinet Hinge FAQ</b></a>
                <div class=small>Some frequently asked questions (and answers!)
                        about cabinet hinges.
                </div>
				</li>
				<li>
                <a href="hinge-howto.html"><b>Cabinet Hinge How-To</b></a>
                <div class=small>Get some help identifying the type and/or size
				of your cabinet hinges.
                </div>
				</li>
				<li>
                <a href="hinge-howto-vid.html"><b>Cabinet Hinge How-To Videos</b></a>
                <div class=small>Watch these videos for more help identifying the type and/or size
				of your cabinet hinges .
                </div>
				</li>
				<li>
                <a href="hinge-help.html"><b>Cabinet Hinge Help</b></a>
                <div class=small>Get some help replacing cabinet hinges and/or
				mounting plates.
                </div>
				</li>
 <!--           <li>
                <a href="cabinet-hinge-styles.html"><b>Cabinet Hinge Styles</b></a>
                <div class=small>Learn about the different styles of cabinet hinges.
                </div></li>
        -->
                <li>
                <a href="blum-hinges.html"><b>Blum Concealed Hinge Program</b></a>
                <div class=small>All about the Blum European style concealed hinges
                and mounting plates.
                </div>
				</li>
				<li>
                <a href="grass-hinges.html"><b>Grass Concealed Hinge Program</b></a>
                <div class=small>Learn more about the Grass series of European
				style concealed cabinet hinges and baseplates.
                </div>
				</li>

                </ul>
        </div>
        </td>
        </tr>
        </table>

</td>
</tr>
</table>

    <div id="pageFooter">

      <div class="pageFooterBox"><span><a href="knobs-pulls.phtml">Cabinet Knobs & Pulls</a></span>
 		<ul>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66000">Handle Pulls</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66002">Cabinet Knobs</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66001">Cup Pulls</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66006">Bar Pulls</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66007">Appliance Pulls</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66004">Backplates</a></li>
          <li><a href="cgi-bin/usastore.pl?a=b&cnid=66003">Ring, Bail & Pendant</a></li>
          </ul>
	 </div>
	<div class="pageFooterBox"><span><a href="hinges.phtml">Cabinet Hinges</a></span>
		<ul>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66020">Inset</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66021">Overlay</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66030">Euro</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66025">Knife</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66024">Concealed</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66028">Semi-Concealed</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66029">Non-Concealed</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66022">Side Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66023">Surface Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66027">Specialty</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66026">Mounting Plates</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66032">Miscellaneous</a></li>
		</ul>
	</div>
    <div class="pageFooterBox"><span><a href="drawer-slides.phtml">Drawer Slides</a></span>
		<ul>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66040">3/4 Extension</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66041">Full Extension</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66042">Overtravel</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66044">Side Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66045">Side/Bottom Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66046">Under Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66047">Flat Mount</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66043">Specialty</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66048">Miscellaneous</a></li>
		</ul>
	</div>
    <div class="pageFooterBox"><span><a href="catches-locks.phtml">Catches & Locks</a></span>
		<ul>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66060">Magnetic Catches</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66061">Roller Catches</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66062">Mechanical Catches</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66063">Ball & Bullet Catches</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66064">Cam Locks</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66065">Deabolt Locks</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66066">Gang Locks</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66068">Other Locks</a></li>
			<li><a href="cgi-bin/usastore.pl?a=b&cnid=66067">Lock Accessories</a></li>
		</ul>
	</div>
    <div class="pageFooterBox"><span><a href="customer-care.html">Customer Care</a></span>
                <ul>
                <li><a href="policies.html#returns">Returns</a></li>
                <li><a href="policies.html#shipping">Shipping & Handling</a></li>
                <li><a href="policies.html#privacy">Privacy & Security</a></li>
                <li><a href="contact.html">Contact Us</a></li>
                <li><a href="care-faq.html">Customer Care FAQ</a></li>
                </ul>
	</div>



        <div id="copy">
        Copyright &copy; 2013 usacabinethardware.com by Everything Direct Inc.<br>
        1046 39th Ave W<br>
        West Fargo, ND 58078<br>
        1.866.570.3272<br>
        <a href="mailto:webadmin@usacabinethardware.com">webadmin</a>
        </div>
	</div>

</div>
</body>
</html>

